version: "1.9"

image: docker.8x8.com:5000/8x8/hyperloop/centos7/python3.7 

buildInfo:
  buildName: av-flask-hello-world-internship
  buildDescription: av-flask-hello-world-internship

sonar:
  qgName: av-flask-hello-world-internship
  projectName: av-flask-hello-world-internship
  blockerIssueThreshold: 50
  coverageThreshold: 0
  smellsCountThreshold: 5000
  unitTestSuccessThreshold: 0

deploy: false

ci:
  enabled: true
cd:
  enabled: false

stages:
  verify:
  security:
  publish:
    artifact:
      docker:
        - build 8x8/av-flask-hello-world-internship:$ART_VERSION ./docker/ ./docker/Dockerfile
        - push 8x8/av-flask-hello-world-internship:$ART_VERSION
      helm:
        - push helm/av-flask-hello-world-chart
