---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 804064231264.dkr.ecr.us-east-1.amazonaws.com/hello-world-flask-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
