---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: {{ .Values.image }}
        resources:
          limits:
            memory: {{ .Values.resource-limits.memory | quote }}
            cpu: {{ .Values.resource-limits.cpu | quote }}
        ports: 
        - containerPort: {{ .Values.ports.container-port }}
