---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{ .Values.service.labels }}
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
    - port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.containerPort }}
