apiVersion: v1
kind: Service
metadata:
  name: {{ include "av-flask-hello-world-chart.fullname" . }}
  labels:
{{ include "av-flask-hello-world-chart.labels" . | indent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: av-flask-intership.acceptance.cloud.8x8.com
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "av-flask-hello-world-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
